MOD bulk commit to setup Signed-off-by: Zdenek Styblik <stybla@turnovfree.net>
This is a bulk commit of modifications made to setup scripts. It brings new
features, new bugs and changes to the scripts resp. some shuffling around. It
also replaces some % echo; calls with % printf;.
Scripts utilize awk more now, because awk seems to be better fit to do the job
than shell.

diff --git a/setup/Checklist b/setup/Checklist
--- a/setup/Checklist
+++ b/setup/Checklist
@@ -10,28 +10,32 @@
 # Created: 19/09/2005 by vonatar
 # Last Revision: 05/08/2006 by vonatar
 #
-
 if [ ! -e '/etc/Kickstart.cfg' ]; then
-	echo "File '/etc/Kickstart.cfg' not found."
-	echo "Exitting checklist."
+	printf "File '/etc/Kickstart.cfg' not found.\nExitting checklist."
 	checklist_failed
 	exit 1
 fi
-
+#
 . /etc/Kickstart.cfg
-
 # Includes common functions
 . /usr/lib/setup/include/functions.inc
 . /usr/lib/setup/include/installer.inc
-
+#
 clear
-
-echo
-echo "#########################"
-echo "# Pre-install Checklist #"
-echo "#########################"
-echo
-
+#
+printf "\n#########################\n"
+printf "# Pre-install Checklist #\n"
+printf "#########################\n\n"
+# To prevent Get_Kickstart() loop. 'no-ks-get' is expected.
+NOKSGET=${1:-''}
+#
+rm -f /tmp/CDROM
+rm -f /tmp/CHECKLIST_FAILED
+rm -f /tmp/NETWORK_UP
+rm -f /tmp/NONET
+rm -f /tmp/NetworkSettings
+rm -f /tmp/Partitions
+#
 ######################
 # Network card check #
 ######################
@@ -43,53 +47,57 @@ echo
 # if false, we need to load kernel
 # modules hoping to find the right one.
 #
-if [ ${ETH} ] && ! ip link show dev "${ETH}" > /dev/null 2>&1 ; then
+awk -f /usr/lib/setup/GetNetSettings.awk \
+	/etc/Kickstart.cfg > /tmp/NetworkSettings
 #
-# No ethernet card support in Kernel.
-# 
-	rm -f /tmp/Modules.info
-	echo "Your kernel has no built-in support for ethernet card!"
-	echo "Probing for MCA, ISA, and PCI network cards: "
-# Note ~ don't we have an udev for this kind of stuff???
-	for CARD in 3c59x acenic de4x5 dgrs eepro100 e1000 tg3 epic100 hp100 ne2k-pci olympic \
-		pcnet32 rcpci 8139too 8139cp sktr tulip via-rhine yellowfin dl2k ns83820 \
-		depca ibmtr 3c501 3c503 3c505 3c507 3c509 3c515 ac3200 \
-		acenic at1700 cosa cs89x0 de4x5 de600 \
-		de620 e2100 eepro eexpress es3210 eth16i ewrk3 fmv18x forcedeth hostess_sv11 \
-		hp-plus hp lne390 ne3210 ni5010 ni52 ni65 sb1000 sealevel smc-ultra \
-		sis900 smc-ultra32 smc9194 wd virtio_net; do
-		modprobe "${CARD}" > /dev/null 2>&1
-		if ip link show dev "${ETH}" > /dev/null 2>&1 ; then
-			echo "Found: $CARD card."
-			echo "/sbin/modprobe $CARD" > /tmp/Modules.info
-			break
-		fi
-	done
-#
-# If /tmp/Modules.info does not
-# exist or is empty, we did not
-# found an ethernet module.
-#
-# The installation can proceed without
-# network support ONLY if PKG server
-# and Kernel repository are on CD-Rom
-#
-	if [ ! -s /tmp/Modules.info ]; then
-		if [ "${PKG_SRC}" = "cdrom" ]; then
-			touch /mnt/NONET
-			echo "No ethernet card found." 
-		else
-			touch "/tmp/CHECKLIST_FAILED"
-			echo
-			echo "FATAL ERROR on Ethernet card - Aborting"
-			echo "I'm sorry, I did not found a kernel "
-			echo "module for your Ethernet card."
-			FireBugInfo
-			exit 1
-		fi # if PKG_SRC
-	fi # if ! -s /tmp/Modules
-fi # if ip link
-
+for IFACE in $(cut -d ',' -f 1 /tmp/NetworkSettings | \
+	grep -E -e '^[a-z]+[0-9]+$'	| sort | uniq); do
+	if ! ip link show dev "${IFACE}" > /dev/null 2>&1 ; then
+	#
+	# No ethernet card support in Kernel.
+	# 
+		rm -f /tmp/Modules.info
+		echo "Your kernel has no built-in support for ethernet card!"
+		echo "Probing for MCA, ISA, and PCI network cards: "
+		# Note ~ don't we have an udev for this kind of stuff???
+		for CARD in 3c59x acenic de4x5 dgrs eepro100 e1000 tg3 epic100 hp100 \
+			ne2k-pci olympic pcnet32 rcpci 8139too 8139cp sktr \
+			tulip via-rhine yellowfin dl2k ns83820 \
+			depca ibmtr 3c501 3c503 3c505 3c507 3c509 3c515 ac3200 \
+			acenic at1700 cosa cs89x0 de4x5 de600 de620 e2100 \
+			eepro eexpress es3210 eth16i ewrk3 fmv18x forcedeth hostess_sv11 \
+			hp-plus hp lne390 ne3210 ni5010 ni52 ni65 sb1000 sealevel smc-ultra \
+			sis900 smc-ultra32 smc9194 wd virtio_net; do
+			modprobe "${CARD}" > /dev/null 2>&1
+			if ip link show dev "${IFACE}" > /dev/null 2>&1 ; then
+				echo "Found: $CARD card."
+				echo "/sbin/modprobe $CARD" > /tmp/Modules.info
+				break
+			fi
+		done # for CARD
+		#
+		# If /tmp/Modules.info does not
+		# exist or is empty, we did not
+		# found an ethernet module.
+		#
+		# The installation can proceed without
+		# network support ONLY if PKG server
+		# and Kernel repository are on CD-Rom
+		#
+		if [ ! -s /tmp/Modules.info ]; then
+			if [ "${PKG_SRC}" = "cdrom" ]; then
+				touch /mnt/NONET
+				printf "No ethernet card found.\n" 
+			else
+				touch "/tmp/CHECKLIST_FAILED"
+				printf "\nFATAL ERROR on Ethernet card - Aborting\n"
+				printf "No kernel module could be found for your Ethernet card.\n"
+				FireBugInfo
+				exit 1
+			fi # if PKG_SRC
+		fi # if ! -s /tmp/Modules
+	fi # if ip link
+done # for IFACE
 #######################
 # Sets up the network #
 #######################
@@ -99,16 +107,99 @@ fi # if ip link
 #
 if [ ! -e /tmp/NONET ]; then
 	if [ ! -e /tmp/NETWORK_UP ]; then
-		/bin/sh /etc/rc.d/rc.inet1 start && touch /tmp/NETWORK_UP
+		for IFACE in $(cut -d ',' -f 1 /tmp/NetworkSettings | \
+			grep -E -e '^[a-z]+[0-9]+$'	| sort | uniq); do
+			if ! /bin/ip link show dev "${IFACE}" &>/dev/null ; then
+				printf "Device '%s' doesn't seem to be present!\n" "${IFACE}"
+				continue
+			fi
+			/bin/ip link set up dev "${IFACE}"
+			/bin/ip address flush dev "${IFACE}"
+			if [ $(grep -e "${IFACE},DHCP" /tmp/NetworkSettings | \
+				cut -d '=' -f 2) = 'yes' ]; then
+				if [ -e "/var/run/udhcpc.${IFACE}.pid" ]; then
+					kill $(cat "/var/run/udhcpc.${IFACE}.pid") >/dev/null
+					rm -f "/var/run/udhcpc.${IFACE}.pid"
+				fi
+				/sbin/udhcpc -i "${IFACE}" -p "/var/run/udhcpc.${IFACE}.pid" \
+					-s /etc/udhcpc/default.script -R -b
+			else
+				IPADDR=$(grep -E -e "^${IFACE},IP[0-9]+=" /tmp/NetworkSettings | \
+					cut -d '=' -f 2)
+				MASK=$(grep -E -e "^${IFACE},MASK[0-9]+=" /tmp/NetworkSettings | \
+					cut -d '=' -f 2)
+				if [ -z "${IPADDR}" ] || [ -z "${MASK}" ]; then
+					printf "IP address('%s') or Netmask('%s') missing for '%s'.\n" \
+						"${IPADDR}" "${MASK}" "${IFACE}"
+					continue
+				fi
+				if /bin/ip address add "${IPADDR}/${MASK}" dev "${IFACE}" ; then
+					printf "Set '%s/%s' for '%s'.\n" "${IPADDR}" "${MASK}" "${IFACE}"
+				else
+					printf "Failed to set '%s/%s' for '%s'\n" "${IPADDR}" \
+						"${MASK}" "${IFACE}"
+				fi # if /bin/ip addr add
+			fi # if DHCP
+			touch /tmp/NETWORK_UP
+		done # for IFACE
+		#
+		printf "Adding Domain Name Servers into /etc/resolv.conf.\n"
+		grep -e '^NAMESERVER=' /tmp/NetworkSettings | cut -d '=' -f 2 | \
+			xargs printf "nameserver %s\n" >> /etc/resolv.conf
+		#
+		for GW in $(grep -e '^GW=' /tmp/NetworkSettings | cut -d '=' -f 2); do
+			printf "Adding default route via '%s'.\n" "${GW}"
+			/bin/ip route add default via "${GW}"
+		done
 	fi # if ! -e /tmp/NET
-#
-# Ntpdate is executed only if network is UP
-#
+	
+	KHOSTNAME=''
+	KDOMAIN=''
+	IFS=' '
+	for KPARAM in $(cat /proc/cmdline); do
+		if printf "%s" "${KPARAM}" | grep -q -e '^KS=' ; then
+			KS=$(printf "%s" "${KPARAM}" | cut -d '=' -f 2-)
+			continue
+		elif printf "%s" "${KPARAM}" | grep -q -e '^HOSTNAME=' ; then
+			KHOSTNAME=$(printf "%s" "${KPARAM}" | cut -d '=' -f 2-)
+			continue
+		elif printf "%s" "${KPARAM}" | grep -q -e '^DOMAIN=' ; then
+			KDOMAIN=$(printf "%s" "${KPARAM}" | cut -d '=' -f 2-)
+			continue
+		fi # if printf ...
+	done # for KPARAM
+	IFS='
+'
+	# HOSTNAME passed via kernel param and no iface has DHCP -> KHOSTNAME
+	if [ -n "${KHOSTNAME}" ] \
+		&& ! grep -q -E -e '^eth[0-9]+,DHCP[0-9]+=yes' /tmp/NetworkSettings ; then
+		#
+		HOSTNAME=$KHOSTNAME
+		if [ -n "${KDOMAIN}" ]; then
+			DOMAIN=$KDOMAIN
+		fi
+	elif grep -q -E -e '^eth[0-9]+,DHCP[0-9]+=yes' /tmp/NetworkSettings ; then
+		HOSTNAME=$(hostname | cut -d '.' -f 1)
+		DOMAIN=$(hostname | cut -d '.' -f 2-)
+	fi
+	# Alternate Kickstart.cfg file
+	if [ "${NOKSGET}" != 'no-ks-get' ] && [ ! -z "${KS}" ]; then
+		printf "KS keyword found in Kickstart.cfg.\n"
+		if [ "${NOKSGET}" != 'no-ks-get' ] && Get_Kickstart "${KS}" \
+			&& [ -s /tmp/Kickstart.cfg.new ]; then
+			#
+			mv /tmp/Kickstart.cfg.new /etc/Kickstart.cfg
+			exec /usr/lib/setup/Checklist no-ks-get
+		else
+			printf "Continuing with default '/etc/Kickstart.cfg'.\n"
+		fi
+	fi # if [ ! -z "${KS}" ]
+	#
+	# Ntpdate is executed only if network is UP
 	if [ -e /tmp/NETWORK_UP -a "${NTPHOST}" != "none" ]; then
 		printf "Syncing clock with %s ..... " "${NTPHOST}"
 		if /usr/sbin/ntpdate "${NTPHOST}" > /dev/null 2>&1 ; then
-			echo "[OK]"
-			printf "Saving date on hardware clock ....." && \
+			printf "[OK]\nSaving date on hardware clock ....." && \
 				/usr/sbin/hwclock --${HWCLOCK} --systohc > /dev/null 2>&1 && \
 				echo "[OK]" || echo "[FAILED]"
 		else 
@@ -121,20 +212,23 @@ fi # if ! -e /tmp/NET
 #############
 #
 # Checks if $DEVICE is supported
-# 
-DEV=$(basename "${BOOTDEV}")
-printf "Checking if '${DEVICE}' is supported ... "
-if ! cat /proc/partitions | grep -e "${DEV}" > /dev/null 2>&1 ; then
-	# fatal error
-	touch /tmp/CHECKLIST_FAILED
-	printf "[FAILED]\n\n\n"
-	echo "FATAL ERROR: cannot access '${DEVICE}' - Aborting"
-	echo "HINT: Does this kernel support '${DEVICE}' ?"
-	FireBugInfo
-	exit 1
-else
-	printf "[OK]\n\n"
-fi
+rm -f /tmp/Partitions
+awk -f /usr/lib/setup/GetPartitions.awk /etc/Kickstart.cfg > /tmp/Partitions
+for DEV in $(awk -F':' '{ print $1 }' /tmp/Partitions | sort | uniq); do
+	printf "Checking if '${DEV}' is supported ... "
+	DEVICE=$(basename "${DEV}")
+	if ! grep -q -e "${DEVICE}" /proc/partitions /dev/null 2>&1 ; then
+		# fatal error
+		touch /tmp/CHECKLIST_FAILED
+		printf "[FAILED]\n\n"
+		printf "FATAL ERROR: cannot access '%s' - Aborting\n" "${DEVICE}"
+		printf "HINT: Does this kernel support '%s' ?\n" "${DEVICE}"
+		FireBugInfo
+		exit 1
+	else
+		printf "[OK]\n"
+	fi # if ! grep -q -e "${DEVICE}" ...
+done # for DEV
 ############################
 # Scans for a cdrom device #
 ############################
@@ -145,7 +239,6 @@ fi
 if [ ! -e /tmp/CDROM ] && [ "${PKG_SRC}" = "cdrom" ]; then
 	Scan_CD
 fi
-
 ########################
 # PACKAGE_SERVER check #
 ########################
@@ -159,10 +252,10 @@ if [ "${PKG_SRC}" = "ftp" -o "${PKG_SRC}" = "http" ]; then
 	if [ ! -s /mnt/CHECKSUMS.md5 ]; then
 		touch /tmp/CHECKLIST_FAILED
 		printf "[FAILED]\n\n"
-		echo "FATAL ERROR: PKG server '${PACKAGE_SERVER}'"
-		echo "FATAL ERROR: is unreachable - Aborting"
-		echo "HINT: Check network configuration."
-		echo "HINT: Check if your PKG server is alive!"
+		printf "FATAL ERROR: PKG server '%s'\n" "${PACKAGE_SERVER}"
+		printf "FATAL ERROR: is unreachable - Aborting\n"
+		printf "HINT: Check network configuration.\n"
+		printf "HINT: Check if your PKG server is alive!\n"
 		FireBugInfo
 		exit 1
 	fi # if ! -s 
@@ -182,17 +275,26 @@ if [ "${PKG_SRC}" = "nfs" ]; then
 	NFS_Mount "${PACKAGE_SERVER}"
 	#
 	# Check CHECKSUMS.md5 on NFS share
-	#
 	if [ ! -s /var/log/mount/CHECKSUMS.md5 ]; then
-		touch "/tmp/CHECKLIST_FAILED"
+		touch /tmp/CHECKLIST_FAILED
 		printf " [FAILED]\n\n"
-		echo "FATAL ERROR: Cannot find ${DISTRO} root on NFS  - Aborting"
-		echo "HINT: Check PKG repository path in /etc/Kickstart.cfg"
-		echo "HINT: Path must point to ${DISTRO} root"
+		printf "FATAL ERROR: Cannot find %s root on NFS  - Aborting\n" "${DISTRO}"
+		printf "HINT: Check PKG repository path in /etc/Kickstart.cfg\n"
+		printf "HINT: Path must point to %s root\n" "${DISTRO}"
 		FireBugInfo
 		exit 1
 	fi
 	umount  /var/log/mount
 	echo "[OK]"
 fi # if PKG_SRC = nfs
+# TAG list file
+printf "\nChecking tag list ..."
+if Get_Tag_List "${TAG}" && [ -s /tmp/taglist ] ; then
+	printf " [OK]\n"
+else
+	touch /tmp/CHECKLIST_FAILED
+	printf " [FAILED]\n\n"
+	printf "FATAL ERROR: Cannot fetch tag list - Aborting\n"
+	FireBugInfo
+fi
 ### END of /usr/lib/setup/Checklist
diff --git a/setup/CreatePartitions b/setup/CreatePartitions
--- a/setup/CreatePartitions
+++ b/setup/CreatePartitions
@@ -21,40 +21,29 @@
 if ! ps aux | grep -e 'udevd' | grep -q -v -e 'grep' ; then
 	/usr/sbin/makedevs.sh > ${REDIR} 2>&1
 fi
+for DRIVE in $(awk -F':' '{ print $1 }' /tmp/Partitions | sort | uniq); do
+	# Clear MBR & Partition table
+	dd if=/dev/zero of=${DRIVE} bs=512 count=1 > ${REDIR} 2>&1
+	# Create partitions
+	printf "Creating partitions on %s..... " "${DRIVE}"
+	grep -e "^${DRIVE}" /tmp/Partitions | awk -F':' '{ print $5 }' | \
+		sfdisk --no-reread --force ${DRIVE} -uM > ${REDIR} 2>&1
+	# Test Partitions
+	if ! sfdisk -V ${DRIVE} > ${REDIR} 2>&1 ; then
+		printf "[FAIL]\n"
+		printf "\nFATAL ERROR on partitions table - Aborting\n"
+		printf "HINT: Check tty4 for errors.\n"
+		printf "HINT: Partitions exceeding %s size ?\n" ${DRIVE}
+		FireBugInfo
+		exit 1
+	else
+		printf "[OK]\n"
+	fi # if ! sfdisk -V ...
+done # for DRIVE
 #
-# Clears MBR & Partition table
-#
-dd if=/dev/zero of=${BOOTDEV} bs=512 count=1 > ${REDIR} 2>&1
-#
-# Creates partitions
-#
-printf "Creating partitions on %s..... " "${BOOTDEV}"
-cat /tmp/SFDiskPartitionsList | \
-	sfdisk --no-reread --force ${BOOTDEV} -uM > ${REDIR} 2>&1
-#
-# Test Partitions
-#
-if ! sfdisk -V ${BOOTDEV} > ${REDIR} 2>&1 ; then
-	printf "\nFATAL ERROR on partitions table - Aborting\n"
-	printf "HINT: Check tty4 for errors.\n"
-	printf "HINT: Partitions exceeding %s size ?\n" ${BOOTDEV}
-	FireBugInfo
-	exit 1
-fi
-#
-# Makes the first partition bootable
-# -N number
-# Change only the single partition indicated. For example:
-#  % sfdisk /dev/hdb -N5
-#  ,,,*
-#  %
-#
-echo ",,,*" | sfdisk --force ${BOOTDEV} -N1 > ${REDIR} 2>&1
-#
-# Device creation: now we need to create
-# dev nodes for the new partitions
+# Device creation: now we need to create dev nodes for the new partitions
 # Note: makedev command seems to be gone.
 if ! ps aux | grep -e 'udevd' | grep -q -v -e 'grep'; then
 	/usr/sbin/makedevs.sh > ${REDIR} 2>&1
 fi
-printf "[OK]\n\n"
+# EOF
diff --git a/setup/SeTlilo b/setup/SeTlilo
--- a/setup/SeTlilo
+++ b/setup/SeTlilo
@@ -18,24 +18,19 @@
 # includes common functions
 . /usr/lib/setup/include/functions.inc
 #
+awk -f /usr/lib/setup/GetBootinfo.awk /etc/Kickstart.cfg > /tmp/Bootinfo
 # Moving created fstab to destination disk
-#
 mv /tmp/fstab /mnt/etc/fstab
 touch /mnt/etc/mtab
-#
-# Checks if using smart_array or ataraid
-#
-Check_Smart_Array
+LOCATION=$(grep -e '^LOCATION=' /tmp/Bootinfo | cut -d '=' -f 2)
 # Note: this is for PXE boots which won't need any bootloader
-if [ ! -e /mnt/sbin/lilo ] || [ ! -x /mnt/sbin/lilo ]; then
-	echo
-	echo "LiLO not found or not executable."
-	echo "You forgot to install LiLO or installing PXE machine."
-	echo "Skipping LiLO installation."
-	echo
+if [ ! -e /mnt/sbin/lilo ] || [ ! -x /mnt/sbin/lilo ] \
+	|| [ "${LOCATION}" = 'none' ]; then
+	printf "\nLILO not found or not executable.\n"
+	printf "You forgot to install LILO or installing PXE machine.\n"
+	printf "Skipping LILO installation.\n\n"
 	exit 0
-fi
-
+fi # if [ ! -e /mnt/sbin/lilo
 #
 # If kernel name is 'bzImage'
 # it's better to rename it as:
@@ -51,8 +46,31 @@ if [ "${KERN}" = "bzImage" ]; then
 	mv "/mnt/boot/${KERN}" "/mnt/boot/${KNAME}"
 else
 	KNAME="${KERN}"
-fi
+fi # if [ "${KERN}" ...
 
+if [ -z "${ROOTPART}" ]; then
+	ROOTPART=$(Get_Root_Partition)
+	if [ -z "${ROOTPART}" ]; then
+		printf "\nRoot Partition not set - Aborting.\n"
+		FireBugInfo
+		exit 1
+	fi # if [ -z "${ROOTPART}" ]
+fi # if [ -z "${ROOTPART}" ]
+BOOTDEV=$(grep -e '^BOOTDEV=' /tmp/Bootinfo | cut -d '=' -f 2)
+if [ -z "${BOOTDEV}" ]; then
+	BOOTDEV=$(cut -d ':' -f 1 /tmp/Partitions | head -n 1)
+	if [ -z "${BOOTDEV}" ]; then
+		printf "\nBOOTDEV not found. Unable to install LILO.\n\n"
+		FireBugInfo
+		exit 1
+	fi # if [ -z "${BOOTDEV}" ]
+fi # if [ -z "${BOOTDEV}" ]
+#
+# Makes the first partition bootable. Change only the single partition indicated. 
+# For example:
+#  % sfdisk /dev/hdb -N5
+#  ,,,*
+echo ",,,*" | sfdisk --force ${BOOTDEV} -N1 > ${REDIR} 2>&1
 #------------------------------------------
 # Creates lilo.conf
 #------------------------------------------
@@ -65,10 +83,11 @@ cat << EOF1 > /mnt/etc/lilo.conf
 boot = ${BOOTDEV}
 EOF1
 # FIX/Workaround to boot from VirtIO disks
-if printf "%s" "${BOOTDEV}" | grep -q -E -e '/dev/vd[a-z]+' ; then
-	printf "disk=${BOOTDEV} bios=0x80 max-partitions=7\n" >> /mnt/etc/lilo.conf
-	cp -apr ${BOOTDEV}* /mnt/dev/
-fi
+for VDD in $(cut -d ':' -f 1 /tmp/Partitions | \
+	grep -E -e '/dev/vd[a-z]+' | sort | uniq); do
+	printf "disk=${VDD} bios=0x80 max-partitions=7\n" >> /mnt/etc/lilo.conf
+	cp -apr ${VDD}* /mnt/dev/
+done # for VDD
 
 cat << EOF2 >> /mnt/etc/lilo.conf
 lba32
@@ -96,18 +115,15 @@ EOF2
 # Installs lilo
 #
 clear
-echo "###################"
-echo "# Installing LILO #"
-echo "###################"
-echo
+printf "###################\n"
+printf "# Installing LILO #\n"
+printf "###################\n"
 if ! chroot /mnt /sbin/lilo -v 1>/dev/null 2>"${REDIR}" ; then
-	echo
-	echo "FATAL ERROR installing lilo! - Aborting"
+	printf "\nFATAL ERROR installing lilo! - Aborting\n"
 	FireBugInfo
 	exit 1
 else
-	echo
-	echo "Installed."
-	echo
+	printf "\nInstalled.\n\n"
 	sleep 1
-fi
+fi # if ! chroot /mnt ...
+# EOF
diff --git a/setup/SeTpartitions b/setup/SeTpartitions
--- a/setup/SeTpartitions
+++ b/setup/SeTpartitions
@@ -15,24 +15,20 @@
 . /usr/lib/setup/include/functions.inc
 . /usr/lib/setup/include/filesystem.inc
 #########################################################
-#							#
-#	FORMATTING PARTITIONS				#
-#							#
+#                                                       #
+#	FORMATTING PARTITIONS                                 #
+#                                                       #
 #########################################################
-#
-# Checks if using smart_array or ataraid
-#
-Check_Smart_Array
 #
 # Getting the list of Linux partitions
 # and formatting them with the choosen 
 # filesystem.
 #
-echo "Formatting partitions on ${DEVICE}:"
-for FS in $(cat /tmp/FilesystemsList); do
+printf "Going to format partitions.\n"
+for DEVLINE in $(cat /tmp/Partitions); do
+	FS=$(printf "%s" "${DEVLINE}" | awk -F':' '{ print $4 }')
 	# see if this partition has a filesystem associated
-	FS2=$(printf "%s\n" ${FS} | cut -d " " -f 2)
-	case "$FS2" in
+	case "$FS" in
 		'xfs')
 			COMMAND="make_xfs"
 			;;
@@ -57,11 +53,12 @@ for FS in $(cat /tmp/FilesystemsList); do
 			INODES=4096
 			CHECK="n"
 	esac
+	DEVICE=$(printf "%s" "${DEVLINE}" | cut -d ':' -f 1)
+	DEVICE=$(Check_Smart_Array "${DEVICE}")
+	PARTITION_DEVICE=$(printf "%s" "${DEVLINE}" | cut -d ':' -f 2)
+	PARTITION_DEVICE="${DEVICE}${PARTITION_DEVICE}"
 
-	PART_NUMBER=$(printf "%s\n" ${FS} | cut -d " " -f 1)
-	PARTITION_DEVICE="${DEVICE}${PART_NUMBER}"
-
-	printf "${PARTITION_DEVICE} [${FS2}] ..... "
+	printf "${PARTITION_DEVICE} [${FS}] ..... "
 	if $COMMAND ${PARTITION_DEVICE} ${INODES} ${CHECK} ; then
 		printf "\t[ OK ]\n"
 	else
@@ -70,39 +67,47 @@ for FS in $(cat /tmp/FilesystemsList); do
 		echo "HINT: Check tty4 for errors during format."
 		FireBugInfo
 		exit 1
-	fi
-done # for FS
+	fi # if $COMMAND $PARTITION ...
+done # for DEVLINE
 #
 # Now, we MUST mount root partition on /mnt
-#
 if [ ! -d /mnt ]; then
 	mkdir /mnt
-fi
-mount "${ROOTPART}" /mnt
+fi # if [ ! -d /mnt ]
+ROOTPART=${ROOTPART:-''}
+if [ -z "${ROOTPART}" ]; then
+	ROOTPART=$(Get_Root_Partition)
+	if [ -z "${ROOTPART}" ]; then
+		printf "Root partition not set - Aborting.\n"
+		FireBugInfo
+		exit 1
+	fi # if [ -z "${ROOTPART}" ]
+fi # if [ -z "${ROOTPART}" ]
 #
-# Check if mount was successfull.
-#
-if [ $? -ne 0 ]; then
-	printf "\nFATAL ERROR mounting root partition %s - Aborting" "${ROOTPART}\n"
-	echo "HINT: Check tty4 for errors."
+# Check if we can mount ROOTPART.
+if ! mount "${ROOTPART}" /mnt ; then
+	printf "\nFATAL ERROR mounting root partition %s - Aborting\n" "${ROOTPART}"
+	printf "HINT: Check tty4 for errors.\n"
 	FireBugInfo
 	exit 1
-fi
+fi # if ! mount "${ROOTPART}"
 
-for MOUNT in $(cat /tmp/MountpointsList); do
-	MOUNTPOINT=$(printf "%s\n" ${MOUNT} | cut -d " " -f 2)
-	MOUNTPARSED=$(printf "%s\n" ${MOUNT} | cut -d " " -f 1)
+for DEVLINE in $(cat /tmp/Partitions | cut -d ':' -f 1-3); do
+	MOUNTPOINT=$(printf "%s\n" "${DEVLINE}" | cut -d ':' -f 3)
+	MOUNTPARSED=$(printf "%s\n" "${DEVLINE}" | cut -d ':' -f 2)
+	DEVICE=$(printf "%s\n" "${DEVLINE}" | cut -d ':' -f 1)
 	MOUNT_DEVICE="${DEVICE}${MOUNTPARSED}"
 	
 	if [ "${MOUNT_DEVICE}" = ${ROOTPART} ]; then
 		continue
-	fi
+	fi # if [ "${MOUNT_DEVICE}" ...
 
 	if [ "${MOUNTPOINT}" = "swap" ]; then
 		# Activate swap partition(s)
 		/sbin/swapon "${MOUNT_DEVICE}" > "${REDIR}" 2>&1
 		continue
-	fi
+	fi # if [ "${MOUNTPOINT}" ...
 	mkdir -p "/mnt${MOUNTPOINT}"
 	mount "${MOUNT_DEVICE}" "/mnt${MOUNTPOINT}"
-done
+done # for DEVLINE 
+# EOF
diff --git a/setup/setup b/setup/setup
--- a/setup/setup
+++ b/setup/setup
@@ -49,11 +49,30 @@ export PATH
 
 clear
 
-echo
-echo "##########################"
-echo "# Starting installation! #"
-echo "##########################"
-echo
+printf "\n##########################\n"
+printf "# Starting installation! #\n"
+printf "##########################\n\n"
+# Get TAG list first, because there is no point to continue on fail.
+printf "Getting TAG list ..."
+if Get_Tag_List "${TAG}" && [ -s /tmp/taglist ]; then
+	printf " [OK]\n"
+else
+	printf " [FAILED]\n\n"
+	printf "FATAL ERROR - unable to fetch TAG list - Aborting.\n"
+	FireBugInfo
+	exit 1
+fi # if Get_Tag_List ...
+# Run pre-installation scripts, if any.
+if [ -n "${PREINST}" ]; then
+	IFS=','
+	for PRESCRIPT in ${PREINST}; do
+		if [ ! -e "/etc/pre-install/${PRESCRIPT}" ]; then
+			printf "Pre-install script '%s' doesn't seem to exist.\n" "${PRESCRIPT}"
+			continue
+		fi # if [ ! -e ...
+		/etc/pre-install/${PRESCRIPT}
+	done # for PRESCRIPT
+fi # if [ -n "${PREINST}" ]
 #
 # Creates:
 #
@@ -62,11 +81,11 @@ echo
 # - SFDiskPartList
 # - fstab
 #
-Extract_Info 2 > /tmp/MountpointsList
-Extract_Info 3 > /tmp/FilesystemsList
-Extract_Info 4 > /tmp/SFDiskPartitionsList
+#Extract_Info 2 > /tmp/MountpointsList
+#Extract_Info 3 > /tmp/FilesystemsList
+#Extract_Info 4 > /tmp/SFDiskPartitionsList
 #
-Check_Smart_Array
+awk -f /usr/lib/setup/GetPartitions.awk /etc/Kickstart.cfg > /tmp/Partitions
 #
 Create_Fstab
 #
@@ -90,16 +109,12 @@ CreatePartitions && SeTpartitions && Raptor && SeTlilo && SeTnetwork && SeTconfi
 # runs the final tasks
 #
 if [ -e /tmp/Kickstart.END ]; then
-	# 
 	# Cleanup
-	#
 	rm -rf /mnt/usr/Download
 	rm -f /mnt/etc/mtab
 	rm -f /mnt/PkgList.txt
 	rm -f /mnt/CHECKSUMS.md5
-	#
 	# Run postinstall script
-	#
 	if [ -s /etc/postinstall.sh ]; then
 		cp /etc/postinstall.sh /mnt/postinstall.sh
 		chmod +x /mnt/postinstall.sh
@@ -107,10 +122,10 @@ if [ -e /tmp/Kickstart.END ]; then
 		rm /mnt/postinstall.sh
 	fi
 	if [ -n "${POSTINST}" ]; then
-		IFS=","
+		IFS=','
 		for POSTSCRIPT in ${POSTINST}; do
 			if [ ! -e "/etc/post-install/${POSTSCRIPT}" ]; then
-				printf "Post-install script '%s' doesn't seem to exist." \
+				printf "Post-install script '%s' doesn't seem to exist.\n" \
 					${POSTSCRIPT}
 				continue
 			fi # if ! -e ...
@@ -119,33 +134,24 @@ if [ -e /tmp/Kickstart.END ]; then
 			chroot /mnt ./${POSTSCRIPT} || true
 			rm -f /mnt/${POSTSCRIPT}
 		done # for POSTSCRIPT
-		IFS=""
+		IFS=''
 	fi # if -n POSTSCRIPT
-	#
 	# Installation ends!
-	#
 	echo -e \\a
-	echo "Installation complete."
-	echo 
-	#
-	# Ejects CD-Rom before reboot
-	#
+	printf "Installation complete.\n\n"
+	# Eject CD-Rom before reboot
 	if [ -s /tmp/CDROM ] && [ -x /bin/eject ]; then
 		/bin/eject $(cat /tmp/CDROM)
 	fi
-	#
-	# If AUTOSTART=yes umounts all partitions
-	# and reboots the system 
-	#
+	# If AUTOSTART=yes umounts all partitions and reboots the system
 	if [ "$AUTOSTART" = "yes" ]; then
 		umount -a
 		echo "Rebooting system in 5 seconds!!"
 		sleep 5
 		reboot
 	else
-		echo
-		echo "You can reboot now"
-		echo
-	fi
-fi
+		printf "\nYou can reboot now\n\n"
+	fi # if [ "${AUTOSTART}" = "yes" ]
+fi # if [ -e /tmp/Kickstart.END ]
 # end slackware setup script
+# EOF
