MOD setup/ - replace bashisms
Commit replaces bashisms and adds couple fixes as well.
Cumulative commit.

Signed-off-by: Zdenek Styblik <stybla@turnovfree.net>

diff --git a/setup/CreatePartitions b/setup/CreatePartitions
--- a/setup/CreatePartitions
+++ b/setup/CreatePartitions
@@ -19,31 +19,34 @@
 # Creates device nodes
 # Note: makedev command seems to be gone
 if ! ps aux | grep -e 'udevd' | grep -q -v -e 'grep' ; then
-	/usr/sbin/makedevs.sh > ${REDIR} 2>&1
+	/usr/sbin/makedevs.sh >> "${FH_LOG}" 2>&1
 fi
-for DRIVE in $(awk -F':' '{ print $1 }' /tmp/Partitions | sort | uniq); do
+for DRIVE in $(awk -F':' '{ print $1 }' "${TMP}/Partitions" | sort | uniq); do
 	# Clear MBR & Partition table
-	dd if=/dev/zero of=${DRIVE} bs=512 count=1 > ${REDIR} 2>&1
+	dd if=/dev/zero of=${DRIVE} bs=512 count=1 >> "${FH_LOG}" 2>&1
 	# Create partitions
-	printf "Creating partitions on %s..... " "${DRIVE}"
-	grep -e "^${DRIVE}" /tmp/Partitions | awk -F':' '{ print $5 }' | \
-		sfdisk --no-reread --force ${DRIVE} -uM > ${REDIR} 2>&1
+	printf "Creating partitions on %s..... " "${DRIVE}" | \
+		tee -a "${FH_LOG}"
+	grep -e "^${DRIVE}" "${TMP}/Partitions" | \
+		awk -F':' '{ print $5 }' | \
+		sfdisk --no-reread --force ${DRIVE} -uM >> "${FH_LOG}" 2>&1
 	# Test Partitions
-	if ! sfdisk -V ${DRIVE} > ${REDIR} 2>&1 ; then
-		printf "[FAIL]\n"
-		printf "\nFATAL ERROR on partitions table - Aborting\n"
-		printf "HINT: Check tty4 for errors.\n"
-		printf "HINT: Partitions exceeding %s size ?\n" ${DRIVE}
+	if ! sfdisk -V ${DRIVE} >> "${FH_LOG}" 2>&1 ; then
+		printf "[FAIL]\n" | tee -a "${FH_LOG}"
+		printf "\nFATAL ERROR on partitions table - Aborting\n" | \
+			tee -a "${FH_LOG}"
+		printf "HINT: Check tty4 for errors.\n" | tee -a "${FH_LOG}"
+		printf "HINT: Partitions exceeding %s size ?\n" "${DRIVE}" |\
+			tee -a "${FH_LOG}"
 		FireBugInfo
 		exit 1
-	else
-		printf "[OK]\n"
 	fi # if ! sfdisk -V ...
+	printf "[OK]\n" | tee -a "${FH_LOG}"
 done # for DRIVE
 #
 # Device creation: now we need to create dev nodes for the new partitions
 # Note: makedev command seems to be gone.
 if ! ps aux | grep -e 'udevd' | grep -q -v -e 'grep'; then
-	/usr/sbin/makedevs.sh > ${REDIR} 2>&1
+	/usr/sbin/makedevs.sh >> "${FH_LOG}" 2>&1
 fi
 # EOF
diff --git a/setup/SeTlilo b/setup/SeTlilo
--- a/setup/SeTlilo
+++ b/setup/SeTlilo
@@ -18,17 +18,18 @@
 # includes common functions
 . /usr/lib/setup/include/functions.inc
 #
-awk -f /usr/lib/setup/GetBootinfo.awk /etc/Kickstart.cfg > /tmp/Bootinfo
+awk -f /usr/lib/setup/GetBootinfo.awk /etc/Kickstart.cfg > "${TMP}/Bootinfo"
 # Moving created fstab to destination disk
-mv /tmp/fstab /mnt/etc/fstab
+mv "${TMP}/fstab" /mnt/etc/fstab
 touch /mnt/etc/mtab
-LOCATION=$(grep -e '^LOCATION=' /tmp/Bootinfo | cut -d '=' -f 2)
+LOCATION=$(grep -e '^LOCATION=' "${TMP}/Bootinfo" | awk -F'=' '{ print $2 }')
 # Note: this is for PXE boots which won't need any bootloader
 if [ ! -e /mnt/sbin/lilo ] || [ ! -x /mnt/sbin/lilo ] \
 	|| [ "${LOCATION}" = 'none' ]; then
-	printf "\nLILO not found or not executable.\n"
-	printf "You forgot to install LILO or installing PXE machine.\n"
-	printf "Skipping LILO installation.\n\n"
+	printf "\nLILO not found or not executable.\n" | tee -a "${FH_LOG}"
+	printf "Either you haven't installed LILO\n" | tee -a "${FH_LOG}"
+	printf "or you're installing PXE machine.\n" | tee -a "${FH_LOG}"
+	printf "Skipping LILO installation.\n\n" | tee -a "${FH_LOG}"
 	exit 0
 fi # if [ ! -e /mnt/sbin/lilo
 #
@@ -41,7 +42,7 @@ if [ ! -d /mnt/boot ]; then
 	mkdir /mnt/boot
 fi
 if [ "${KERN}" = "bzImage" ]; then 
-	KVERSION=$(uname -a | cut -d " " -f 3)
+	KVERSION=$(uname -a | awk -F' ' '{ print $3 }')
 	KNAME="vmlinuz-${KVERSION}"
 	mv "/mnt/boot/${KERN}" "/mnt/boot/${KNAME}"
 else
@@ -51,16 +52,18 @@ fi # if [ "${KERN}" ...
 if [ -z "${ROOTPART}" ]; then
 	ROOTPART=$(Get_Root_Partition)
 	if [ -z "${ROOTPART}" ]; then
-		printf "\nRoot Partition not set - Aborting.\n"
+		printf "\nRoot Partition not set - Aborting.\n" | \
+			tee -a "${FH_LOG}"
 		FireBugInfo
 		exit 1
 	fi # if [ -z "${ROOTPART}" ]
 fi # if [ -z "${ROOTPART}" ]
-BOOTDEV=$(grep -e '^BOOTDEV=' /tmp/Bootinfo | cut -d '=' -f 2)
+BOOTDEV=$(grep -e '^BOOTDEV=' "${TMP}/Bootinfo" | awk -F'=' '{ print $2 }')
 if [ -z "${BOOTDEV}" ]; then
-	BOOTDEV=$(cut -d ':' -f 1 /tmp/Partitions | head -n 1)
+	BOOTDEV=$(awk -F':' '{ print $1 }' "${TMP}/Partitions" | head -n 1)
 	if [ -z "${BOOTDEV}" ]; then
-		printf "\nBOOTDEV not found. Unable to install LILO.\n\n"
+		printf "\nBOOTDEV not found. Unable to install LILO.\n\n" |\
+			tee -a "${FH_LOG}"
 		FireBugInfo
 		exit 1
 	fi # if [ -z "${BOOTDEV}" ]
@@ -70,7 +73,7 @@ fi # if [ -z "${BOOTDEV}" ]
 # For example:
 #  % sfdisk /dev/hdb -N5
 #  ,,,*
-echo ",,,*" | sfdisk --force ${BOOTDEV} -N1 > ${REDIR} 2>&1
+echo ",,,*" | sfdisk --force ${BOOTDEV} -N1 >> "${FH_LOG}" 2>&1
 #------------------------------------------
 # Creates lilo.conf
 #------------------------------------------
@@ -84,8 +87,9 @@ boot = ${BOOTDEV}
 EOF1
 
 # FIX/Workaround to boot from VirtIO disk
-if printf "%s" "${BOOTDEV}" | grep -q -E -e '/dev/vd[a-z]+'; then
-	printf "disk=${BOOTDEV} bios=0x80 max-partitions=7\n" >> /mnt/etc/lilo.conf
+if printf -- "%s" "${BOOTDEV}" | grep -q -E -e '/dev/vd[a-z]+'; then
+	printf "disk=%s bios=0x80 max-partitions=7\n" \
+		"${BOOTDEV}" >> /mnt/etc/lilo.conf
 fi
 
 cp -apr $BOOTDEV* /mnt/dev/
@@ -118,15 +122,15 @@ EOF2
 # Installs lilo
 #
 clear
-printf "###################\n"
-printf "# Installing LILO #\n"
-printf "###################\n"
-if ! chroot /mnt /sbin/lilo -v 1>/dev/null 2>"${REDIR}" ; then
-	printf "\nFATAL ERROR installing lilo! - Aborting\n"
+printf "###################\n" | tee -a "${FH_LOG}"
+printf "# Installing LILO #\n" | tee -a "${FH_LOG}"
+printf "###################\n" | tee -a "${FH_LOG}"
+if ! chroot /mnt /sbin/lilo -v 1>/dev/null 2>>"${FH_LOG}" ; then
+	printf "\nFATAL ERROR installing lilo! - Aborting\n" |\
+		tee -a "${FH_LOG}"
 	FireBugInfo
 	exit 1
-else
-	printf "\nInstalled.\n\n"
-	sleep 1
 fi # if ! chroot /mnt ...
+printf "\nLILO Installed.\n\n" | tee -a "${FH_LOG}"
+sleep 1
 # EOF
diff --git a/setup/SeTpartitions b/setup/SeTpartitions
--- a/setup/SeTpartitions
+++ b/setup/SeTpartitions
@@ -25,8 +25,8 @@
 # filesystem.
 #
 printf "Going to format partitions.\n"
-for DEVLINE in $(cat /tmp/Partitions); do
-	FS=$(printf "%s" "${DEVLINE}" | awk -F':' '{ print $4 }')
+for DEVLINE in $(cat "${TMP}/Partitions"); do
+	FS=$(printf -- "%s" "${DEVLINE}" | awk -F':' '{ print $4 }')
 	# see if this partition has a filesystem associated
 	case "$FS" in
 		'xfs')
@@ -53,21 +53,21 @@ for DEVLINE in $(cat /tmp/Partitions); do
 			INODES=4096
 			CHECK="n"
 	esac
-	DEVICE=$(printf "%s" "${DEVLINE}" | cut -d ':' -f 1)
+	DEVICE=$(printf -- "%s" "${DEVLINE}" | awk -F':' '{ print $1 }')
 	DEVICE=$(Check_Smart_Array "${DEVICE}")
-	PARTITION_DEVICE=$(printf "%s" "${DEVLINE}" | cut -d ':' -f 2)
+	PARTITION_DEVICE=$(printf -- "%s" "${DEVLINE}" | \
+		awk -F':' '{ print $2 }')
 	PARTITION_DEVICE="${DEVICE}${PARTITION_DEVICE}"
 
-	printf "${PARTITION_DEVICE} [${FS}] ..... "
-	if $COMMAND ${PARTITION_DEVICE} ${INODES} ${CHECK} ; then
-		printf "\t[ OK ]\n"
-	else
-		printf "\t[FAIL]\n"
-		printf "\nFATAL ERROR formatting %s - Aborting\n" "${PARTITION_DEVICE}"
-		printf "HINT: Check '%s' for errors during format." "${REDIR}"
+	printf -- "${PARTITION_DEVICE} [${FS}] ..... "
+	if ! $COMMAND ${PARTITION_DEVICE} ${INODES} ${CHECK} ; then
+		printf "\t[FAIL]\n" | tee -a "${FH_LOG}"
+		printf "\nFATAL ERROR formatting %s - Aborting\n" \
+			"${PARTITION_DEVICE}" | tee -a "${FH_LOG}"
 		FireBugInfo
 		exit 1
-	fi # if $COMMAND $PARTITION ...
+	fi # if ! $COMMAND $PARTITION ...
+	printf "\t[ OK ]\n" | tee -a "${FH_LOG}"
 done # for DEVLINE
 #
 # Now, we MUST mount root partition on /mnt
@@ -78,7 +78,8 @@ ROOTPART=${ROOTPART:-''}
 if [ -z "${ROOTPART}" ]; then
 	ROOTPART=$(Get_Root_Partition)
 	if [ -z "${ROOTPART}" ]; then
-		printf "Root partition not set - Aborting.\n"
+		printf "Root partition not set - Aborting.\n" | \
+			tee -a "${FH_LOG}"
 		FireBugInfo
 		exit 1
 	fi # if [ -z "${ROOTPART}" ]
@@ -86,16 +87,17 @@ fi # if [ -z "${ROOTPART}" ]
 #
 # Check if we can mount ROOTPART.
 if ! mount "${ROOTPART}" /mnt ; then
-	printf "\nFATAL ERROR mounting root partition %s - Aborting\n" "${ROOTPART}"
-	printf "HINT: Check '%s' for errors.\n" "${REDIR}"
+	printf "\nFATAL ERROR mounting root partition %s - Aborting\n" \
+		"${ROOTPART}" | tee -a "${FH_LOG}"
 	FireBugInfo
 	exit 1
 fi # if ! mount "${ROOTPART}"
 
-for DEVLINE in $(cat /tmp/Partitions | cut -d ':' -f 1-3); do
-	MOUNTPOINT=$(printf "%s\n" "${DEVLINE}" | cut -d ':' -f 3)
-	MOUNTPARSED=$(printf "%s\n" "${DEVLINE}" | cut -d ':' -f 2)
-	DEVICE=$(printf "%s\n" "${DEVLINE}" | cut -d ':' -f 1)
+for DEVLINE in $(cat "${TMP}/Partitions" | \
+	awk -F':' '{ printf "%s:%s:%s\n", $1, $2, $3 }'); do
+	MOUNTPOINT=$(printf "%s\n" "${DEVLINE}" | awk -F':' '{ print $3 }')
+	MOUNTPARSED=$(printf "%s\n" "${DEVLINE}" | awk -F':' '{ print $2 }')
+	DEVICE=$(printf "%s\n" "${DEVLINE}" | awk -F':' '{ print $1 }')
 	MOUNT_DEVICE="${DEVICE}${MOUNTPARSED}"
 	
 	if [ "${MOUNT_DEVICE}" = ${ROOTPART} ]; then
@@ -104,7 +106,7 @@ for DEVLINE in $(cat /tmp/Partitions | cut -d ':' -f 1-3); do
 
 	if [ "${MOUNTPOINT}" = "swap" ]; then
 		# Activate swap partition(s)
-		/sbin/swapon "${MOUNT_DEVICE}" > "${REDIR}" 2>&1
+		/sbin/swapon "${MOUNT_DEVICE}" >> "${FH_LOG}" 2>&1
 		continue
 	fi # if [ "${MOUNTPOINT}" ...
 	mkdir -p "/mnt${MOUNTPOINT}"
diff --git a/setup/SlaptGet b/setup/SlaptGet
--- a/setup/SlaptGet
+++ b/setup/SlaptGet
@@ -30,17 +30,18 @@ cd /mnt/usr/Download
 # slapt-get from:
 # http://software.jaos.org
 #
-echo "Package updates from slapt-get"
-echo "Downloading slapt-get from\n\n http://software.jaos.org "
+printf "Package updates from slapt-get\n" | tee -a "${FH_LOG}"
+printf "Downloading slapt-get from http://software.jaos.org" |\
+	tee -a "${FH_LOG}"
 
-if ! wget "${SLAPTGET}" 1 > ${REDIR} 2>&1 ; then
-	echo "ERROR downloading slapt-get - Skipping Autoupdates!" | \
-		tee /mnt/var/log/slapt-get.log
+if ! wget "${SLAPTGET}" >> "${FH_LOG}" 2>&1 ; then
+	printf "ERROR downloading slapt-get - Skipping Autoupdates!\n" | \
+		tee -a /mnt/var/log/slapt-get.log
 	touch /tmp/Kickstart.END
 	exit 0
 fi
 SLAPTPKG=$(basename "${SLAPTGET}")
-/usr/lib/setup/installpkg --root /mnt "${SLAPTPKG}"
+/usr/lib/setup/installpkg --root /mnt "${SLAPTPKG}" 2>&1 | tee -a "${FH_LOG}"
 #
 # If PKG Repository is NFS, is better to point
 # to HTTP or FTP backup PKG servers. 
@@ -88,7 +89,7 @@ echo "####################################"
 echo
 
 echo "Updating PKG list: "
-/usr/sbin/slapt-get --update | tee /var/log/slapt-get.log
+/usr/sbin/slapt-get --update | tee -a /var/log/slapt-get.log
 
 #
 # PKG upgrade
diff --git a/setup/setup b/setup/setup
--- a/setup/setup
+++ b/setup/setup
@@ -24,68 +24,61 @@
 # As always, bug reports, suggestions, etc: volkerdi@slackware.com
 #
 # Modified for
-# Slack-Kickstart 10.2
+# Slack-Kickstart-ng
 #
-# comments to: vonatar@slack-kickstart.org
-# http://www.slack-kickstart.org
-#
-# Last Revision: 20/09/2006 by vonatar
+# Origin: 20/09/2006 vonatar(http://www.slack-kickstart.org)
 #
 # includes common functions
 . /usr/lib/setup/include/functions.inc
-#
-# - Sets env variables
-# - Sets PATH
-#
-REDIR=/dev/tty4
-TMP=/tmp
-#
 if [ ! -d "${TMP}" ]; then
-	mkdir -p "${TMP}"
+	if ! mkdir -p "${TMP}"; then
+		printf "FATAL ERROR - create TMP dir '%s'.\n" "${TMP}" |\
+			tee -a "${FH_LOG}"
+		FireBugInfo
+		exit 1
+	fi
 fi
-
+# Set env variables, set PATH
 PATH="$PATH:/usr/lib/setup"
 export PATH
 
 clear
 
-printf "\n##########################\n"
-printf "# Starting installation! #\n"
-printf "##########################\n\n"
+printf "\n##########################\n" | tee -a "${FH_LOG}"
+printf "# Starting installation! #\n" | tee -a "${FH_LOG}"
+printf "##########################\n\n" | tee -a "${FH_LOG}"
 # Get TAG list first, because there is no point to continue on fail.
-printf "Getting TAG list ..."
-if Get_Tag_List "${TAG}" && [ -s /tmp/taglist ]; then
-	printf " [OK]\n"
-else
-	printf " [FAILED]\n\n"
-	printf "FATAL ERROR - unable to fetch TAG list - Aborting.\n"
+printf "Getting TAG list ..." | tee -a "${FH_LOG}"
+if ! Get_Tag_List "${TAG}" || [ ! -s "${TMP}/taglist" ]; then
+	printf " [FAILED]\n\n" | tee -a "${FH_LOG}"
+	printf "FATAL ERROR - unable to fetch TAG list - Aborting.\n" |\
+		tee -a "${FH_LOG}"
 	FireBugInfo
 	exit 1
-fi # if Get_Tag_List ...
+fi # if ! Get_Tag_List ...
+printf " [OK]\n" | tee -a "${FH_LOG}"
 # Run pre-installation scripts, if any.
 if [ -n "${PREINST}" ]; then
 	IFS=','
-	for PRESCRIPT in ${PREINST}; do
+	for PRESCRIPT in "${PREINST}"; do
 		if [ ! -e "/etc/pre-install/${PRESCRIPT}" ]; then
-			printf "Pre-install script '%s' doesn't seem to exist.\n" "${PRESCRIPT}"
+			printf \
+				"Pre-install script '%s' doesn't seem to exist.\n" \
+				"${PRESCRIPT}" | tee -a "${FH_LOG}"
 			continue
 		fi # if [ ! -e ...
 		/etc/pre-install/${PRESCRIPT}
 	done # for PRESCRIPT
 fi # if [ -n "${PREINST}" ]
-#
-# Creates:
-#
-# - FSList
-# - MPList
-# - SFDiskPartList
-# - fstab
-#
-#Extract_Info 2 > /tmp/MountpointsList
-#Extract_Info 3 > /tmp/FilesystemsList
-#Extract_Info 4 > /tmp/SFDiskPartitionsList
-#
-awk -f /usr/lib/setup/GetPartitions.awk /etc/Kickstart.cfg > /tmp/Partitions
+
+# Creates - FSList, MPList, SFDiskPartList, fstab
+awk -f /usr/lib/setup/GetPartitions.awk /etc/Kickstart.cfg > "${TMP}/Partitions"
+if [ ! -s "${TMP}/Partitions" ]; then
+	printf "FATAL ERROR - Failed to parse out parition info." |\
+		tee -a "${FH_LOG}"
+	FireBugInfo
+	exit 1
+fi
 #
 Create_Fstab
 #
@@ -104,53 +97,54 @@ Create_Fstab
 
 CreatePartitions && SeTpartitions && Raptor && SeTlilo && SeTnetwork && SeTconfig
 
-#
-# If exit status is OK
-# runs the final tasks
-#
-if [ -e /tmp/Kickstart.END ]; then
-	# Cleanup
-	rm -rf /mnt/usr/Download
-	rm -f /mnt/etc/mtab
-	rm -f /mnt/PkgList.txt
-	rm -f /mnt/CHECKSUMS.md5
-	# Run postinstall script
-	if [ -s /etc/postinstall.sh ]; then
-		cp /etc/postinstall.sh /mnt/postinstall.sh
-		chmod +x /mnt/postinstall.sh
-		chroot /mnt /postinstall.sh
-		rm /mnt/postinstall.sh
-	fi
-	if [ -n "${POSTINST}" ]; then
-		IFS=','
-		for POSTSCRIPT in ${POSTINST}; do
-			if [ ! -e "/etc/post-install/${POSTSCRIPT}" ]; then
-				printf "Post-install script '%s' doesn't seem to exist.\n" \
-					${POSTSCRIPT}
-				continue
-			fi # if ! -e ...
-			cp -ap /etc/post-install/${POSTSCRIPT} /mnt
-			chmod +x /mnt/${POSTSCRIPT}
-			chroot /mnt ./${POSTSCRIPT} || true
-			rm -f /mnt/${POSTSCRIPT}
-		done # for POSTSCRIPT
-		IFS=''
-	fi # if -n POSTSCRIPT
-	# Installation ends!
-	printf "Installation complete.\n\n\a"
-	# Eject CD-Rom before reboot
-	if [ -s /tmp/CDROM ] && [ -x /bin/eject ]; then
-		/bin/eject $(cat /tmp/CDROM)
-	fi
-	# If AUTOSTART=yes umounts all partitions and reboots the system
-	if [ "$AUTOSTART" = "yes" ]; then
-		umount -a
-		echo "Rebooting system in 5 seconds!!"
-		sleep 5
-		reboot
-	else
-		printf "\nYou can reboot now\n\n"
-	fi # if [ "${AUTOSTART}" = "yes" ]
-fi # if [ -e /tmp/Kickstart.END ]
+if [ ! -e "${TMP}/Kickstart.END" ]; then
+	printf "Installation ended with ERROR." | tee -a "${FH_LOG}"
+	FireBugInfo
+	exit 1
+fi # if [ ! -e "${TMP}/Kickstart.END" ]
+# If exit status is OK run final tasks
+# Cleanup
+rm -rf /mnt/usr/Download
+rm -f /mnt/etc/mtab
+rm -f /mnt/PkgList.txt
+rm -f /mnt/CHECKSUMS.md5
+# Run postinstall script
+if [ -s /etc/postinstall.sh ]; then
+	cp /etc/postinstall.sh /mnt/postinstall.sh
+	chmod +x /mnt/postinstall.sh
+	chroot /mnt /postinstall.sh
+	rm /mnt/postinstall.sh
+fi
+if [ -n "${POSTINST}" ]; then
+	IFS=','
+	for POSTSCRIPT in ${POSTINST}; do
+		if [ ! -e "/etc/post-install/${POSTSCRIPT}" ]; then
+			printf \
+				"Post-install script '%s' doesn't seem to exist.\n" \
+				"${POSTSCRIPT}" | tee -a "${FH_LOG}"
+			continue
+		fi # if ! -e ...
+		cp -ap /etc/post-install/${POSTSCRIPT} /mnt
+		chmod +x /mnt/${POSTSCRIPT}
+		chroot /mnt ./${POSTSCRIPT} || true
+		rm -f /mnt/${POSTSCRIPT}
+	done # for POSTSCRIPT
+	IFS=''
+fi # if -n POSTSCRIPT
+# Installation ends!
+printf "Installation complete.\n\n\a" | tee -a "${FH_LOG}"
+# Eject CD-Rom before reboot
+if [ -s "${TMP}/CDROM" ] && [ -x /bin/eject ]; then
+	/bin/eject $(cat "${TMP}/CDROM")
+fi
+# If AUTOSTART=yes umounts all partitions and reboots the system
+if [ "$AUTOSTART" = "yes" ]; then
+	umount -a
+	printf "Rebooting system in 5 seconds!!!\n" | tee -a "${FH_LOG}"
+	sleep 5
+	reboot
+else
+	printf "\nYou can reboot now\n\n" | tee -a "${FH_LOG}"
+fi # if [ "${AUTOSTART}" = "yes" ]
 # end slackware setup script
 # EOF
